"""Patch execution boundaries; strategies route from canonical PatchAction fields."""

from __future__ import annotations

from typing import Any, Mapping, Protocol

from .models import PatchAction, PatchPlan


class PatchBackend(Protocol):
    def inspect_source(self, source_image: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def prepare_workspace(self, plan_artifact: Mapping[str, Any], *, attempt: int = 1) -> Mapping[str, Any]: ...
    def execute_action(self, action: PatchAction, context: Mapping[str, Any],
                       *, timeout: float) -> Mapping[str, Any]: ...
    def execute_validation(self, command: str, context: Mapping[str, Any],
                           *, timeout: float) -> Mapping[str, Any]: ...
    def finalize_image(self, plan_artifact: Mapping[str, Any], workspace: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def resolve_prebuilt_image(self, action: PatchAction,
                               plan_artifact: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def verify_source_preserved(self, source_identity: Mapping[str, Any]) -> bool: ...
    def create_after_target(self, run_id: str, patched_image: Mapping[str, Any],
                            planned_after: Mapping[str, Any],
                            before_facts: Mapping[str, Any]) -> tuple[Mapping[str, Any], Mapping[str, Any]]: ...
